//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EuroBuld.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Processed_customer_orders
    {
        public int ID_Processed_customer_orders { get; set; }
        public Nullable<int> ID_Customer_orders { get; set; }
        public Nullable<int> ID_Staff { get; set; }
        public Nullable<int> ID_Foreman { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Date_Start { get; set; }
        public Nullable<System.DateTime> Date_Ending { get; set; }
        public string Final_sum { get; set; }
    
        public virtual Customer_orders Customer_orders { get; set; }
        public virtual Foremen Foremen { get; set; }
        public virtual Staff Staff { get; set; }


    }
}
