//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EuroBuld.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int ID_Request { get; set; }
        public Nullable<int> ID_Service { get; set; }
        public Nullable<System.DateTime> Request_Date { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string Email { get; set; }
        public string Additional_Info { get; set; }
        public string Status { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
