//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EuroBuld.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int ID_Staff { get; set; }
        public Nullable<int> ID_Role { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public byte[] Image { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string Patronymic { get; set; }
        public string Passport_details { get; set; }
        public Nullable<System.DateTime> Date_birth { get; set; }
        public Nullable<System.DateTime> Date_employment { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
