//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursWork_EuroBild_.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customers()
        {
            this.customers_order = new HashSet<customers_order>();
        }
    
        public int ID_customers { get; set; }
        public Nullable<int> ID_Users { get; set; }
        public Nullable<int> ID_service { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customers_order> customers_order { get; set; }
        public virtual service service { get; set; }
        public virtual Users Users { get; set; }
    }
}
