//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursWork_EuroBild_.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EuroBuldEntities : DbContext
    {
        public EuroBuldEntities()
            : base("name=EuroBuldEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customers> customers { get; set; }
        public virtual DbSet<customers_order> customers_order { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<service> service { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
